server:
      port: 8088
      tomcat:
        url-encoding: utf-8
spring:
      datasource:
         driver-class-name: com.mysql.jdbc.Driver
         username: root
         password: 123456
         url: jdbc:mysql://localhost:3306/db_pss?characterEncoding=UTF-8&serverTimezone=GMT%2B8
         type: com.alibaba.druid.pool.DruidDataSource
      aop:
        auto: true
        proxy-target-class: false
      http:
        encoding:
          charset: UTF-8
          enabled: true
      activemq:
        broker-url: tcp://localhost:61616
        in-memory: true
        pool:
          enabled: false
logging:
      level:
        com:
          erp:
            dao: debug
